project:
  type: website
  output-dir: docs

website:
  title: "Eilidh Slater"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: favorite_projects.qmd
        text: My Favorite Projects

format:
  html:
    theme: minty
    css: styles.css
    toc: true
    page-layout: full

editor: visual

